[project]
name = "modelolinguagem"
version = "1.0.0"
authors = [
    {name = " Osmar de Oliveira Braz Junior", email = "osmar.braz@udesc.br"},
]
description = "Multilingual text embeddings"
readme = "README.md"
requires-python = "==3.6.0"
keywords = ["Transformer", "embedding", "texto", "sentença", "palavra", "token"]
license = {text = "MIT"}
classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3.6",
        "Topic :: Scientific/Engineering :: Artificial Intelligence"]
		
dependencies = [
		"transformers==4.26.1", 
		"spacy==3.5.2"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
	 
[tool.setuptools.packages.find]
where = ["src"]  # Lista das pastas que contêm o pacote (["."] por default)